version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: inventory_db
      MYSQL_USER: inventory_user
      MYSQL_PASSWORD: inventory_password
    ports:
      - "3306:3306"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  tomcat:
    image: tomcat:10.1
    container_name: tomcat_container
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    volumes:
      - ./target/inventory-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/ROOT.war

volumes:
  mysql_data:

networks:
  inventory_network:
    driver: bridge